<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>النظام الإلكترونى لإدارة شئون أعضاء هيئة التدريس</title>
    <link rel="stylesheet" href="../css/all.min.css">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/style.css">
</head>
<body class="body">
    <div class="bodyCover"></div>
    <?php
        include('header.php');

    ?>
    <!-- start search and add member button -->
    <div class="container-fluid mt-3">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-2">
                <div class="addMember">
                    <button class="addMemberBtn rounded-pill w-100 border-0" id="addMemberBtn">إضافة عضو جديد</button>
                </div>
            </div>
            <div class="col-md-6">
                <div class="search">
                    <form action="">
                        <input type="text" class="searchField form-control w-100 rounded-pill border-0 px-4" name="search" placeholder="بحث...">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- end search and add member button -->

    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo, doloribus voluptate dolorem asperiores excepturi ipsam expedita aperiam temporibus ullam, omnis, magnam ipsa et porro soluta molestiae cupiditate veritatis ea in? Quis soluta odit similique voluptate ut inventore dicta enim, culpa distinctio tempore neque doloremque autem animi omnis natus ab velit, repellat cupiditate. Illum tempore labore consequuntur deserunt iste nobis asperiores fuga doloribus suscipit tempora voluptas voluptatem distinctio quidem atque, voluptatibus harum eum tenetur aspernatur dicta. Laboriosam at perferendis culpa maxime excepturi ad minima ab quasi dolor? Atque repellendus, quibusdam accusamus sunt aliquam, minima eligendi odio, ab laboriosam praesentium dolorem? Error!</p>











    <?php
        include('footer.php');
    ?>

    <script src="../js/all.min.js"></script>
    <script src="../js/bootstrap.bundle.min.js"></script>
    <script src="../js/main.js"></script>
</body>
</html>